title: Matthew Cheng
logo: /assets/img/profile-picture.jpg
description: "\"Becoming is better than being\" ― Carol Dweck, <em>Mindset: The New Psychology of Success</em>"
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
